# Generated by Django 5.2.12 on 2026-03-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='casco_devolvido',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entrega',
            name='casco_enviado',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entrega',
            name='isopor_devolvido',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entrega',
            name='isopor_enviado',
            field=models.IntegerField(default=0),
        ),
    ]
