# Generated by Django 5.2.12 on 2026-03-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_entrega_casco_devolvido_entrega_casco_enviado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrega',
            name='casco_devolvido',
        ),
        migrations.RemoveField(
            model_name='entrega',
            name='isopor_devolvido',
        ),
        migrations.AlterField(
            model_name='entrega',
            name='casco_enviado',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='isopor_enviado',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
