# Generated by Django 5.2.12 on 2026-03-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_entrega_casco_devolvido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrega',
            name='casco_enviado',
        ),
        migrations.RemoveField(
            model_name='entrega',
            name='isopor_enviado',
        ),
        migrations.AddField(
            model_name='entrega',
            name='casco_devolvido',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entrega',
            name='isopor_devolvido',
            field=models.IntegerField(default=0),
        ),
    ]
