# Generated by Django 5.2.12 on 2026-03-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_entrega_casco_enviado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='casco_enviado',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='entrega',
            name='isopor_enviado',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='casco_devolvido',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='isopor_devolvido',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
