# Generated by Django 5.2.12 on 2026-03-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_entrega_casco_enviado_entrega_isopor_enviado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='foto_isopor',
            field=models.ImageField(blank=True, null=True, upload_to='entregas/'),
        ),
    ]
